version: '3'
services:
  httpd:
    image: ddd-test-httpd
    container_name: ddd-test-httpd
    build:
      context: ./.docker
      dockerfile: nginx.Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
        DOCKER_PROJECT_DIR: ${DOCKER_PROJECT_DIR}
    environment:
      TIMEZONE: ${TIMEZONE}
    ports:
      - ${HTTPD_PORT}:80
    volumes:
      - ./:${DOCKER_PROJECT_DIR}:ro
      - ./.docker/etc/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
  app:
    image: ddd-test-app
    container_name: ddd-test-app
    build:
      context: ./.docker
      dockerfile: app.Dockerfile
      args:
        DOCKER_PROJECT_DIR: ${DOCKER_PROJECT_DIR}
        TIMEZONE: ${TIMEZONE}
        XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
        XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT}
        XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
    environment:
      TIMEZONE: ${TIMEZONE}
    working_dir: /${DOCKER_PROJECT_DIR}
    volumes:
      - ./:${DOCKER_PROJECT_DIR}:rw
    tty: true
  composer:
    image: ddd-test-composer
    container_name: ddd-test-composer
    build:
      context: ./.docker
      dockerfile: composer.Dockerfile
      args:
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        DOCKER_PROJECT_DIR: ${DOCKER_PROJECT_DIR}
        TIMEZONE: ${TIMEZONE}
    environment:
       TIMEZONE: ${TIMEZONE}
    restart: 'no'
    volumes:
      - ./:${DOCKER_PROJECT_DIR}
    depends_on:
      - app